# Generated by Django 4.2.30 on 2026-09-09 08:28

import ImamFlex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImamFlex', '0012_remove_khutbah_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='khutbah',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='khutbah/', validators=[ImamFlex.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='khutbah',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
